## 服务端口
#server:
#  port: 8008
## 服务名
#spring:
#  application:
#    name: service-statistic
#  # 环境设置：dev、test、prod
#  profiles:
#    active: dev
#  # mysql数据库连接
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/guli_college?serverTimezone=GMT%2B8
#    username: root
#    password: 666666
#  #返回数据库的日期格式 !!!
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:com/example/edustatistic/mapper/xml/*.xml
#  type-aliases-package: com.example.edustatistic.mapper
##  global-config:
##    db-config:
##      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
##      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
##      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#ribbon:
#  ConnectTimeout: 5000 #请求连接的超时时间，默认时间为1秒
#  ReadTimeout: 5000 #请求处理的超时时间
#feign:
#  hystrix:
#    enabled: true #开启Hystrix熔断功能
#
